version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/porthos
    overwrite: yes

hooks:
  ApplicationStart:
    - location: appspec-script/start.sh
      timeout: 60
      runas: root

