version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/porothos
    overwrite: yes

hooks:
  ApplicationStop:
    - location: appspec-script/stop.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: appspec-script/start.sh
      timeout: 60
      runas: root

