version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/porothos

hooks:
  ApplicationStop:
    - location: appspec-script/stop.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: appspec-script/start.sh
      timeout: 60
      runas: ubuntu

