version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: porthos-dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: porthos
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - /var/porthos/mysql:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: porthos-dev-redis
    command: ["redis-server", "--requirepass", "noticore1!"]
    ports:
      - "6379:6379"
    volumes:
      - /var/porthos/redis:/data
