spring:
  config:
    import:
      - mysql.yml
      - slack.yml
      - jwt.yml
      - redis.yml
  application:
    name: noticore

logging:
  level:
    root: info


---
spring.config.activate.on-profile: local

spring:
  config:
    import:
      - optional:classpath:env.properties

logging:
  level:
    root: INFO


---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: qa

---
spring.config.activate.on-profile: prod