
---
spring.config.activate.on-profile: local

spring:
  jpa:
    database: MySQL
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:noticore}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnect=true&rewriteBatchedStatements=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:1234}

logging:
  level:
    ROOT: INFO

---
spring.config.activate.on-profile: dev

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pjh-side-dev-rds-standard.cluster-cvhrq7qa1p3t.ap-northeast-2.rds.amazonaws.com:13306/porthos?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnect=true&rewriteBatchedStatements=true
    username: porthos
    password: 479TvfIaW3j3EteVViMJ


---
spring.config.activate.on-profile: qa

---
spring.config.activate.on-profile: prod
